# Utilizar la imagen oficial de Python
FROM python:3.12-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar Git (si es necesario para descargar dependencias)
RUN apt-get update && apt-get install -y git

# Copiar los archivos necesarios al contenedor
COPY . .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que corre Flask
EXPOSE 5000

# Comando para ejecutar la aplicación (asegúrate de que la ruta sea correcta)
CMD ["python", "web/app.py"]
